/**
 *- Application index file
 *
 * The app execution starts here
 * auto-generated by create-react-app script
 */

import React from 'react';
import ReactDOM from 'react-dom';

import App from './App.js';

ReactDOM.render(<App />, document.getElementById('container'));

// eof
