/**
 * Application index file – the app execution starts here
 * auto-generated by create-react-app script
 */
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

ReactDOM.render(<App />, document.getElementById('container'));

// eof
