
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Bryntum.Gantt
{

using System;
    using System.Collections.Generic;
    
public partial class Assignment
{

    public override int Id { get; set; }

    public int TaskIdRaw { get; set; }

    public int ResourceIdRaw { get; set; }

    public int Units { get; set; }



    public virtual Resource Resource { get; set; }

    public virtual Task Task { get; set; }

}

}
