
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Bryntum.Gantt
{

using System;
    using System.Collections.Generic;
    
public partial class CalendarInterval
{

    public override int Id { get; set; }

    public int CalendarIdRaw { get; set; }

    public string RecurrentStartDate { get; set; }

    public string RecurrentEndDate { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public Nullable<byte> IsWorkingRaw { get; set; }

    public string Cls { get; set; }



    public virtual Calendar Calendar { get; set; }

}

}
