
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Bryntum.Gantt
{

using System;
    using System.Collections.Generic;
    
public partial class Dependency
{

    public override int Id { get; set; }

    public int FromIdRaw { get; set; }

    public int ToIdRaw { get; set; }

    public Nullable<int> Type { get; set; }

    public string Cls { get; set; }

    public Nullable<decimal> Lag { get; set; }

    public string LagUnit { get; set; }



    public virtual Task FromTask { get; set; }

    public virtual Task ToTask { get; set; }

}

}
