
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Bryntum.Gantt
{

using System;
    using System.Collections.Generic;
    
public partial class TaskSegment
{

    public override int Id { get; set; }

    public int TaskIdRaw { get; set; }

    public System.DateTime StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public Nullable<decimal> Duration { get; set; }

    public string DurationUnit { get; set; }

    public string Cls { get; set; }



    public virtual Task Task { get; set; }

}

}
